name: download file

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - id: repo
        name: Repo Checkout
        uses: actions/checkout@v2

      - id: download
        name: Download file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: "https://www.xrayvip.com/free.yaml"
          location: public/
          file-name: config.yaml

      - id: path
        name: Print the file path
        run: echo "The file was downloaded to ${{ steps.download.outputs.file-path }}"

      - id: commit
        name: Commit files
        uses: zwaldowski/git-commit-action@v1
      - run: echo "${{ steps.commit.outputs.sha }}"
