name: download file

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        id: download-file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: "https://www.xrayvip.com/free.yaml"
          location: ./public
          file-name: config.yaml
      - name: Print the file path
        run: echo "The file was downloaded to ${{ steps.download-file.outputs.file-path }}"
