name: download file

permissions: write-all

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Repo checkout
        uses: actions/checkout@v4
        with:
          path: main

      - id: download
        name: Download file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: "https://www.xrayvip.com/free.yaml"
          location: main/
          file-name: config.yaml

      - id: path
        name: Print the file path
        run: echo "The file was downloaded to ${{ steps.download.outputs.file-path }}"

      - id: push
        name: Push files
        working-directory: ${{github.workspace}}/main
        run: |
          echo ${{ github.workspace }}
          git config --global user.name actions-user
          git config --global user.email "actions@github.com"
          git add *
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
