name: download file

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  download-file:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Repo checkout
        uses: actions/checkout@v4
        with:
          path: main

      - id: download
        name: Download file
        uses: carlosperate/download-file-action@v2
        with:
          file-url: "https://www.xrayvip.com/free.yaml"
          location: public/
          file-name: config.yaml

      - id: path
        name: Print the file path
        run: echo "The file was downloaded to ${{ steps.download.outputs.file-path }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        name: Commit files
        run: git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git pull

          git add *

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
